# 创建持久化存储卷
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi