# 创建服务
apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    app: consul
spec:
  ports:
  - port: 8500
    targetPort: 8500
    nodePort: 31118
  selector:
    app: consul
  type: NodePort